In [3]:
pip install pandas requests duckdb

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.4.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 10,
    "page": 1
}

response = requests.get(url, params=params)
data = response.json()

df = pd.DataFrame(data)

df = df[["id", "symbol", "current_price", "market_cap", "total_volume"]]

df.head()

            id symbol  current_price     market_cap  total_volume
0      bitcoin    btc   80475.000000  1611741080103   34463041977
1     ethereum    eth    2274.420000   274605508248   14667322250
2       tether   usdt       0.999666   189767130961   58709244970
3       ripple    xrp       1.430000    88566079613    2164834519
4  binancecoin    bnb     655.980000    88401527075    1123339744

In [6]:
df.to_csv("crypto_data.csv", index=False)

In [7]:
import duckdb

con = duckdb.connect()

result = con.execute("""
SELECT *
FROM read_csv_auto('crypto_data.csv')
""").fetchdf()

result

             id      symbol  current_price     market_cap  total_volume
0       bitcoin         btc   80475.000000  1611741080103   34463041977
1      ethereum         eth    2274.420000   274605508248   14667322250
2        tether        usdt       0.999666   189767130961   58709244970
3        ripple         xrp       1.430000    88566079613    2164834519
4   binancecoin         bnb     655.980000    88401527075    1123339744
5      usd-coin        usdc       0.999789    77153241839   12605243443
6        solana         sol      94.480000    54625182245    3577410271
7          tron         trx       0.347838    32994795793     490009378
8  figure-heloc  figr_heloc       1.031000    18211545569      21831017
9      dogecoin        doge       0.109001    16816630372    1164573017

In [8]:
result = con.execute("""
SELECT
    id,
    symbol,
    current_price,
    market_cap,
    total_volume,
    market_cap / total_volume AS liquidity_ratio
FROM read_csv_auto('crypto_data.csv')
""").fetchdf()

result

,id,symbol,current_price,market_cap,total_volume,liquidity_ratio
0,bitcoin,btc,80475.000000,1611741080103,34463041977,46.767232
1,ethereum,eth,2274.420000,274605508248,14667322250,18.722266
2,tether,usdt,0.999666,189767130961,58709244970,3.232321
3,ripple,xrp,1.430000,88566079613,2164834519,40.911247
4,binancecoin,bnb,655.980000,88401527075,1123339744,78.695272
5,usd-coin,usdc,0.999789,77153241839,12605243443,6.120726
6,solana,sol,94.480000,54625182245,3577410271,15.269477
7,tron,trx,0.347838,32994795793,490009378,67.335029
8,figure-heloc,figr_heloc,1.031000,18211545569,21831017,834.205093
9,dogecoin,doge,0.109001,16816630372,1164573017,14.440168

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [12]:
from datetime import datetime

df["date"] = datetime.today().date()

In [13]:
import os

file_name = "crypto_data.csv"

if os.path.exists(file_name):
    df.to_csv(file_name, mode='a', header=False, index=False)
else:
    df.to_csv(file_name, index=False)

In [15]:
from google.colab import files
files.download("crypto_data.csv")